saveTask("this is a task")
import save.py
saveTask("task1")
import save.py
   import save.py
import save.py as save
save.py
python save.py
10 / 1 
10 / 0 
try:
    10/0
except ZeroDivisionError:
    print('Caught the division by zero')
10/0
try:
    10/0
except ZeroDivisionError:
    print("caught division zero")
